### ISSUE TITLE
-h option and other issue

### ISSUE THREAD

**Issue by the-c0d3r** [firefoxbug/ddos#1]
D:\GitHub\ddos>python attack.py -h
Traceback (most recent call last):
  File "attack.py", line 119, in <module>
    parse_parameters(sys.argv[1:])
  File "attack.py", line 96, in parse_parameters
    url = args[0]
IndexError: list index out of range

I'm new to github, forgive me if I do anything strange.

D:\GitHub\ddos>python attack.py -t 10 -c1 http://www.site.com
Debug : thread=1 time=10 http://www.site.com
Traceback (most recent call last):
  File "attack.py", line 139, in <module>
    signal.signal(signal.SIGALRM, handler)
AttributeError: 'module' object has no attribute 'SIGALRM'

**Comment by Maslor** [comment]
Which operating system are you running the script on?

**Comment by ghost** [comment]
I am running windows and getting both of these issues.

**Comment by ghost** [comment]
Help would be greatly appreciated.
(I realize that this program is currently *nix-only, but if there's a way to fix it, I'm listening)

**Comment by the-c0d3r** [comment]
[This Pull Request](https://github.com/firefoxbug/ddos/pull/3) solve the crashing if the script is executed with "-h" argument or no argument.
